### ISSUE TITLE
crash in function simos.syscall_info

### ISSUE THREAD

**Issue by quoscient** [angr/angr#166]
The line https://github.com/angr/angr/blob/c60388cddc93ec2c11a28bd0ff95b4cd5ba979f2/angr/simos.py#L108 can cause angr to crash if the generic simos is used.
Since there are no syscalls defined, the statement self.syscall_table.keys() returns an empty sequence. This causes the max() function to raise an exception.

**Comment by ltfish** [comment]
Good catch! If you have time, give us a PR! Otherwise we will fix it in a week (roughly).

**Comment by quoscient** [comment]
I stumbled onto this issue one more time; in the initial report I missed that the same code construct is also used in this line:
https://github.com/angr/angr/blob/2f718925e2f6e3cd109075f4d798ca5130092681/angr/simos.py#L138
Do you mind to reopen the issue?

**Comment by ltfish** [comment]
Seems like really bad code, probably mine :-(

I'll be very busy in the next 48 hours. Someone else should take care of this bug.

**Comment by ltfish** [comment]
Should be fixed with commit 61563de.

**Comment by quoscient** [comment]
Works, thanks

**Comment by brendabrandy** [comment]
Hi I seem to encounter the issue again. I tried to analyze my binary but first the analysis gave me a series of : 
```
vex: priv/guest_arm_toIR.c:14656 (disInstr_ARM_WRK): Assertion `0 == (guest_R15_curr_instr_notENC & 3)' failed.
Traceback:
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(+0x17f696) [0x7f9cdb800696]
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(disInstr_ARM+0xbd) [0x7f9cdb8144ad]
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(bb_to_IR+0x2e5) [0x7f9cdb79ecd5]
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(LibVEX_Translate+0x4ea) [0x7f9cdb74b28a]
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(+0xbd6ba) [0x7f9cdb73e6ba]
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(vex_count_instructions+0xd3) [0x7f9cdb73eb53]
/home/brenda/virtualenvs/angr2/lib/python2.7/site-packages/pyvex/lib/libpyvex.so(vex_block_bytes+0x167) [0x7f9cdb73f067]
```
and then a warning for : 
```
WARNING | 2016-09-20 17:25:50,204 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
```
and then the same crash in syscall_table arises. 

I installed the library through pip install, is it possible that the pip package is not up to date?

**Comment by ltfish** [comment]
The pip package is not up to date indeed. I'm going to make a release soon-ish. Sorry for that.

**Comment by brendabrandy** [comment]
@ltfish I reinstall angr with source package but I still can't get rid of the error. I can't give you the binary either -- do you have any generic work arounds on this issue?

**Comment by ltfish** [comment]
Umm that is weird. I don't think this issue is happening on the latest angr. Can you please open a new issue with a full backtrace of the exception when angr crashes?
